#!/usr/bin/env python3
"""Generate baseline-calibration latent manifests without loading a model."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from epistemic_geometry.benchmarks.e3.base import GENERATOR_VERSION
from epistemic_geometry.benchmarks.e3.splits import (
    CALIBRATION_SPLIT,
    FAMILY_CELLS,
    generate_calibration_manifest,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--seed", type=int, default=20260817)
    parser.add_argument("--n-items", type=int, default=200)
    parser.add_argument(
        "--eligibility",
        type=Path,
        default=Path("configs/q1_v2_structural_eligibility.json"),
    )
    args = parser.parse_args()
    eligibility = json.loads(args.eligibility.read_text(encoding="utf-8"))
    if eligibility.get("generator_version") != GENERATOR_VERSION:
        raise ValueError("structural eligibility was generated by a different generator version")
    if not eligibility.get("structural_approval") or eligibility.get("model_outcomes_used"):
        raise ValueError("structural eligibility is not an approved model-free gate")
    eligible_cells = set(eligibility.get("eligible_cells", []))
    manifests = {}
    for family, cells in FAMILY_CELLS.items():
        for cell in cells:
            if f"{family}/{cell}" not in eligible_cells:
                continue
            manifest = generate_calibration_manifest(
                family, cell, seed=args.seed, n_items=args.n_items
            )
            manifests[f"{family}/{cell}"] = manifest.to_record()
    payload = {
        "suite": "E3-10",
        "split": CALIBRATION_SPLIT,
        "generator_version": GENERATOR_VERSION,
        "model_outcomes": False,
        "structural_gate": {
            "eligibility_file": str(args.eligibility),
            "eligible_cells": sorted(eligible_cells),
            "excluded_cells": sorted(
                set(f"{family}/{cell}" for family, cells in FAMILY_CELLS.items() for cell in cells)
                - eligible_cells
            ),
        },
        "manifests": manifests,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Wrote {args.output} ({len(manifests)} family/cell manifests)")


if __name__ == "__main__":
    main()
