#!/usr/bin/env python3
"""Render the canonical current-status document from ``project_state.yaml``."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
STATE_PATH = ROOT / "project_state.yaml"
OUTPUT_PATH = ROOT / "docs" / "CURRENT_STATUS.md"
README_PATH = ROOT / "README.md"
START = "<!-- PROJECT_STATUS:START -->"
END = "<!-- PROJECT_STATUS:END -->"


def _render_state(state: dict[str, object]) -> str:
    project = state["project"]
    current = state["current"]
    firewall = state["scientific_firewall"]
    instruments = state["instrument_history"]
    assert isinstance(project, dict)
    assert isinstance(current, dict)
    assert isinstance(firewall, dict)
    assert isinstance(instruments, list)
    lines = [
        "# Current Repository Status",
        "",
        "<!-- GENERATED by scripts/render_project_state.py; edit project_state.yaml. -->",
        "",
        f"**Last verified:** {state['last_verified']}",
        f"**Scientific stage:** `{project['scientific_stage']}`",
        f"**Claim status:** `{project['claim_status']}`",
        "",
        "## Current work",
        "",
        str(current["summary"]),
        "",
        f"- Workstream: `{current['workstream']}`",
        f"- RunPod: `{current['runpod']}`",
        f"- GPU work authorized: `{str(current['gpu_work_authorized']).lower()}`",
        f"- New scientific experiment authorized: "
        f"`{str(current['new_scientific_experiment_authorized']).lower()}`",
        f"- Next authorized action: {current['next_authorized_action']}",
        "",
        "## Scientific program",
        "",
        f"- Long-term: {project['long_term_question']}",
        f"- Minimal Q1: {project['minimal_q1']}",
        f"- Q2: {project['q2']}",
        f"- Q3: {project['q3']}",
        "",
        "## Instrument history at a glance",
        "",
        "| Instrument | Status | Evidence boundary |",
        "|---|---|---|",
    ]
    for item in instruments:
        assert isinstance(item, dict)
        lines.append(f"| `{item['id']}` | `{item['status']}` | {item['conclusion']} |")
    lines += [
        "",
        "## Scientific firewall",
        "",
    ]
    for key, value in firewall.items():
        lines.append(f"- `{key}`: `{value}`")
    lines += [
        "",
        "Historical failures above are failures or non-qualification of measurement",
        "instruments. They are not positive or negative tests of the full causal-geometry",
        "theory. The confirmatory holdout remains untouched.",
        "",
        "## Canonical navigation",
        "",
        "Start with [the scientific constitution](SCIENTIFIC_CONSTITUTION.md), then",
        "[metrics and statistics](METRICS_AND_STATISTICS.md), the",
        "[experiment ladder](EXPERIMENT_LADDER.md), and the",
        "[document index](DOCUMENT_INDEX.md). Machine-readable history is in",
        "[`experiments/registry.yaml`](../experiments/registry.yaml).",
        "",
    ]
    return "\n".join(lines)


def _read_state() -> dict[str, object]:
    value = yaml.safe_load(STATE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("project_state.yaml must contain a mapping")
    return value


def _readme_block(state: dict[str, object]) -> str:
    project = state["project"]
    current = state["current"]
    assert isinstance(project, dict) and isinstance(current, dict)
    return "\n".join(
        [
            START,
            f"**Current stage:** `{project['scientific_stage']}` — "
            f"**scientific claim:** `{project['claim_status']}`.",
            "",
            str(current["summary"]),
            "",
            f"**Next authorized action:** {current['next_authorized_action']}",
            END,
        ]
    )


def _replace_readme_block(content: str, block: str) -> str:
    if START not in content or END not in content:
        raise ValueError("README is missing generated project-status markers")
    before, rest = content.split(START, 1)
    _old, after = rest.split(END, 1)
    return before + block + after


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    state = _read_state()
    status = _render_state(state)
    readme = README_PATH.read_text(encoding="utf-8")
    rendered_readme = _replace_readme_block(readme, _readme_block(state))
    if args.check:
        failures = []
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != status:
            failures.append(str(OUTPUT_PATH.relative_to(ROOT)))
        if readme != rendered_readme:
            failures.append(str(README_PATH.relative_to(ROOT)))
        if failures:
            print("stale generated state: " + ", ".join(failures), file=sys.stderr)
            return 1
        print("project state: current")
        return 0
    OUTPUT_PATH.write_text(status, encoding="utf-8")
    README_PATH.write_text(rendered_readme, encoding="utf-8")
    print(f"rendered {OUTPUT_PATH.relative_to(ROOT)} and README status block")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
