#!/usr/bin/env python3
"""Render the canonical current-status document from ``project_state.yaml``."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
STATE_PATH = ROOT / "project_state.yaml"
OUTPUT_PATH = ROOT / "docs" / "CURRENT_STATUS.md"
README_PATH = ROOT / "README.md"
START = "<!-- PROJECT_STATUS:START -->"
END = "<!-- PROJECT_STATUS:END -->"


def _render_state(state: dict[str, object]) -> str:
    project = state["project"]
    current = state["current"]
    firewall = state["scientific_firewall"]
    assert isinstance(project, dict)
    assert isinstance(current, dict)
    assert isinstance(firewall, dict)
    active = current.get("active_experiment", {})
    assert isinstance(active, dict)
    lines = [
        "# Current Repository Status",
        "",
        "<!-- GENERATED by scripts/render_project_state.py; edit project_state.yaml. -->",
        "",
        f"**Last verified:** {state['last_verified']}",
        f"**Scientific stage:** `{project['scientific_stage']}`",
        f"**Claim status:** `{project['claim_status']}`",
        "",
        "## Closed headline results",
        "",
        "- **Q1:** `Q1_CONFIRMATORY_QWEN_PASS_MINISTRAL_FAIL`. The fixed Qwen",
        "  controller passed; the fixed Ministral controller failed mandatory",
        "  validity/evaluability guards.",
        "- **Q2:** `Q2_V4_1_G2`, with independent radial results `RS+` and",
        "  `RT+`. The semantic forensic audit is clean.",
        "- **Q3:** `NOT_RUN`.",
        "",
        "Exact results and scope: [Scientific Results](SCIENTIFIC_RESULTS.md).",
        "",
        "## Active experiment",
        "",
        str(current["summary"]),
        "",
        f"- Workstream: `{current['workstream']}`",
        f"- Evidence level: `{active.get('evidence_level', 'N/A')}`",
        f"- Lifecycle: `{current['lifecycle']}`",
        f"- Branch: `{active.get('branch', 'N/A')}`",
        f"- Authorization commit: `{active.get('authorization_commit', 'N/A')}`",
        f"- Frozen scale: {active.get('families', 'N/A')} question families, "
        f"{active.get('conditions', 'N/A')} conditions, "
        f"{active.get('rollouts', 'N/A')} rollouts, "
        f"{active.get('scheduled_trajectories', 'N/A')} logical trajectories",
        "- Partial scientific outcomes in repository status: `NO`",
        f"- Next authorized action: {current['next_authorized_action']}",
        "",
        "## Scientific firewall",
        "",
        "The open LiveCodeBench campaign remains blind during collection. Its",
        "generated text, correctness, condition-level validity/evaluability,",
        "C/G/D, and controller/null comparisons are not part of this status.",
        "",
        f"- Q1 canonical state: `{firewall['steering']}`",
        f"- Q2 canonical state: `{firewall['geometry_q2']}`",
        f"- Q3 canonical state: `{firewall['committee_q3']}`",
        f"- Free generation: `{firewall['free_generation']}`",
        f"- RunPod: `{current['runpod']}`",
        "",
        "## Canonical navigation",
        "",
        "Read [Start Here](START_HERE.md), [Scientific Results](SCIENTIFIC_RESULTS.md),",
        "the [Experiment Index](EXPERIMENT_INDEX.md), and the",
        "[Claim–Evidence Matrix](CLAIM_EVIDENCE_MATRIX.md). Machine-readable history",
        "is in [`experiments/registry.yaml`](../experiments/registry.yaml).",
        "",
    ]
    return "\n".join(lines)


def _read_state() -> dict[str, object]:
    value = yaml.safe_load(STATE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("project_state.yaml must contain a mapping")
    return value


def _readme_block(state: dict[str, object]) -> str:
    project = state["project"]
    current = state["current"]
    assert isinstance(project, dict) and isinstance(current, dict)
    return "\n".join(
        [
            START,
            f"**Current stage:** `{project['scientific_stage']}` — "
            f"**scientific claim:** `{project['claim_status']}`.",
            "",
            str(current["summary"]),
            "",
            f"**Next authorized action:** {current['next_authorized_action']}",
            END,
        ]
    )


def _replace_readme_block(content: str, block: str) -> str:
    if START not in content or END not in content:
        raise ValueError("README is missing generated project-status markers")
    before, rest = content.split(START, 1)
    _old, after = rest.split(END, 1)
    return before + block + after


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    state = _read_state()
    status = _render_state(state)
    readme = README_PATH.read_text(encoding="utf-8")
    rendered_readme = _replace_readme_block(readme, _readme_block(state))
    if args.check:
        failures = []
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != status:
            failures.append(str(OUTPUT_PATH.relative_to(ROOT)))
        if readme != rendered_readme:
            failures.append(str(README_PATH.relative_to(ROOT)))
        if failures:
            print("stale generated state: " + ", ".join(failures), file=sys.stderr)
            return 1
        print("project state: current")
        return 0
    OUTPUT_PATH.write_text(status, encoding="utf-8")
    README_PATH.write_text(rendered_readme, encoding="utf-8")
    print(f"rendered {OUTPUT_PATH.relative_to(ROOT)} and README status block")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
